### ISSUE TITLE
Record, Pause,Resume, Erase,Resume

### ISSUE THREAD

**Issue by nsmith1024** [dumbgamedev/natCorder#1]
Hello,

I bought your NatCorder from Unity asset store.

Im trying to record video/audio from phone camera where the user can record small sections of audio/video at a time, pausing after each section, being able to review playback that section, then, recording another section, being able to playback review that section, and continuing to do that. Then at the end they will have all the little sections combined into a single video.

I know your system is able to pause and resume recording. But can it pause, play back the recorded portion, then resume recording (appending new recorded video to previously recorded).

Another thing is the user has to also be able to re-record the section over again if they dont like it.

Like this...

1. Start recording first section (video/audio)
2. Pause/stop recording and review (playback what they just recorded)
3. Resume recording a new section
4. Pause/stop recording (playback only that last section they just recorded)
5. If they dont like that last portion, they can re-record it
6. Finally combine all sections into one video.

Is there a way to do that? Maybe i have to create multiple MP4Recorders (a new one after each pause) then combine them all at the end?

**Comment by ericvanderwal** [comment]
I dont own natcorder. This is simply an integration for playmaker.
